spring:
  application:
    name: spring-boot-antlr-example

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: tutorial

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

